name: Java CI with Maven

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Spotless check
        run: mvn -B spotless:check

      - name: Build with Maven
        run: mvn -B verify

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
